set serveroutput on
declare
j_id jobs.job_id%TYPE;
j_ti jobs.job_title%TYPE;
sal_min jobs.min_salary%TYPE;
sal_max jobs.max_salary%TYPE;
TAM_JID EXCEPTION;
TAM_JTIT EXCEPTION;
SAL_NEG EXCEPTION;
SAL_MIN_MAX EXCEPTION;
NULOS EXCEPTION;
begin

j_id:='&j_id';
j_ti:='&j_ti';
sal_min:='&sal_min';
sal_max:='&sal_max';


IF J_ID IS NULL OR J_TI IS NULL OR SAL_MIN IS NULL OR SAL_MAX IS NULL THEN
RAISE NULOS;
END IF;

IF LENGTH(J_ID) <5 OR LENGTH(J_ID)>10 THEN
RAISE TAM_JID;
END IF;

IF LENGTH(J_TI) <5 OR LENGTH(J_TI)>10 THEN
RAISE TAM_JTIT;
END IF;

IF SAL_MIN<=0 OR SAL_MAX<=0 THEN
RAISE SAL_NEG;
END IF;

IF SAL_MIN>=SAL_MAX THEN
RAISE SAL_MIN_MAX;
END IF;


insert into jobs values(j_id,j_ti,sal_min,sal_max);


dbms_output.put_line('INSERT OK');

commit;
exception

when  DUP_VAL_ON_INDEX then
DBMS_OUTPUT.PUT_LINE('DUPLICADO ');
WHEN NULOS THEN
DBMS_OUTPUT.PUT_LINE('ALGUN VALOR NULO ');
WHEN TAM_JID THEN
DBMS_OUTPUT.PUT_LINE('TAMAÑO JOB_ID ERRONEO ');
WHEN TAM_JTIT THEN
DBMS_OUTPUT.PUT_LINE('TAMAÑOJOB_TITLE ERRONEO ');
WHEN SAL_NEG THEN
DBMS_OUTPUT.PUT_LINE('SALARIOS NEGATIVOS ');
WHEN SAL_MIN_MAX THEN
DBMS_OUTPUT.PUT_LINE('MINIMO MAYOR O IGUAL QUE MAXIMO ');


end;